// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Dq_Ph514ECWQEnX_qar05BV4Tg2VPgE',
    appId: '1:1079034001065:web:05b3a962729d6316dd5bb8',
    messagingSenderId: '1079034001065',
    projectId: 'eymp-90579',
    authDomain: 'eymp-90579.firebaseapp.com',
    databaseURL: 'https://eymp-90579-default-rtdb.firebaseio.com',
    storageBucket: 'eymp-90579.appspot.com',
    measurementId: 'G-VYG0Z73BW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTRQRp0Bo3E_NsU1kAiWNamDP4XyR8GhY',
    appId: '1:1079034001065:android:bc8cb00366489e85dd5bb8',
    messagingSenderId: '1079034001065',
    projectId: 'eymp-90579',
    databaseURL: 'https://eymp-90579-default-rtdb.firebaseio.com',
    storageBucket: 'eymp-90579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_Lb5anWtlO9CpFb4wysO5kbRir9vJ90',
    appId: '1:1079034001065:ios:41e9a0c7b53718cbdd5bb8',
    messagingSenderId: '1079034001065',
    projectId: 'eymp-90579',
    databaseURL: 'https://eymp-90579-default-rtdb.firebaseio.com',
    storageBucket: 'eymp-90579.appspot.com',
    androidClientId: '1079034001065-dcifis7682m8j0kdeg70sfv7g8e1mmg0.apps.googleusercontent.com',
    iosBundleId: 'com.me.youthpower.youthPower',
  );
}
